import 'package:islami_app/Core/resources/AssetsManager.dart';
import 'package:islami_app/Core/resources/StringManager.dart';
import 'package:islami_app/model/OnboardingModel.dart';

import '../../Model/SuraModel.dart';

 abstract final class Appconstants {
 static List<Suramodel> surasList = [
    Suramodel(suraNumber: 1, suraNameEn: "Al-Fatiha", suraNameAr: "الفاتحه", suraVerses: 7),
    Suramodel(suraNumber: 2, suraNameEn: "Al-Baqarah", suraNameAr: "البقرة", suraVerses: 286),
    Suramodel(suraNumber: 3, suraNameEn: "Aal-E-Imran", suraNameAr: "آل عمران", suraVerses: 200),
    Suramodel(suraNumber: 4, suraNameEn: "An-Nisa'", suraNameAr: "النساء", suraVerses: 176),
    Suramodel(suraNumber: 5, suraNameEn: "Al-Ma'idah", suraNameAr: "المائدة", suraVerses: 120),
    Suramodel(suraNumber: 6, suraNameEn: "Al-An'am", suraNameAr: "الأنعام", suraVerses: 165),
    Suramodel(suraNumber: 7, suraNameEn: "Al-A'raf", suraNameAr: "الأعراف", suraVerses: 206),
    Suramodel(suraNumber: 8, suraNameEn: "Al-Anfal", suraNameAr: "الأنفال", suraVerses: 75),
    Suramodel(suraNumber: 9, suraNameEn: "At-Tawbah", suraNameAr: "التوبة", suraVerses: 129),
    Suramodel(suraNumber: 10, suraNameEn: "Yunus", suraNameAr: "يونس", suraVerses: 109),
    Suramodel(suraNumber: 11, suraNameEn: "Hud", suraNameAr: "هود", suraVerses: 123),
    Suramodel(suraNumber: 12, suraNameEn: "Yusuf", suraNameAr: "يوسف", suraVerses: 111),
    Suramodel(suraNumber: 13, suraNameEn: "Ar-Ra'd", suraNameAr: "الرعد", suraVerses: 43),
    Suramodel(suraNumber: 14, suraNameEn: "Ibrahim", suraNameAr: "إبراهيم", suraVerses: 52),
    Suramodel(suraNumber: 15, suraNameEn: "Al-Hijr", suraNameAr: "الحجر", suraVerses: 99),
    Suramodel(suraNumber: 16, suraNameEn: "An-Nahl", suraNameAr: "النحل", suraVerses: 128),
    Suramodel(suraNumber: 17, suraNameEn: "Al-Isra", suraNameAr: "الإسراء", suraVerses: 111),
    Suramodel(suraNumber: 18, suraNameEn: "Al-Kahf", suraNameAr: "الكهف", suraVerses: 110),
    Suramodel(suraNumber: 19, suraNameEn: "Maryam", suraNameAr: "مريم", suraVerses: 98),
    Suramodel(suraNumber: 20, suraNameEn: "Ta-Ha", suraNameAr: "طه", suraVerses: 135),
    Suramodel(suraNumber: 21, suraNameEn: "Al-Anbiya", suraNameAr: "الأنبياء", suraVerses: 112),
    Suramodel(suraNumber: 22, suraNameEn: "Al-Hajj", suraNameAr: "الحج", suraVerses: 78),
    Suramodel(suraNumber: 23, suraNameEn: "Al-Mu'minun", suraNameAr: "المؤمنون", suraVerses: 118),
    Suramodel(suraNumber: 24, suraNameEn: "An-Nur", suraNameAr: "النّور", suraVerses: 64),
    Suramodel(suraNumber: 25, suraNameEn: "Al-Furqan", suraNameAr: "الفرقان", suraVerses: 77),
    Suramodel(suraNumber: 26, suraNameEn: "Ash-Shu'ara", suraNameAr: "الشعراء", suraVerses: 227),
    Suramodel(suraNumber: 27, suraNameEn: "An-Naml", suraNameAr: "النّمل", suraVerses: 93),
    Suramodel(suraNumber: 28, suraNameEn: "Al-Qasas", suraNameAr: "القصص", suraVerses: 88),
    Suramodel(suraNumber: 29, suraNameEn: "Al-Ankabut", suraNameAr: "العنكبوت", suraVerses: 69),
    Suramodel(suraNumber: 30, suraNameEn: "Ar-Rum", suraNameAr: "الرّوم", suraVerses: 60),
    Suramodel(suraNumber: 31, suraNameEn: "Luqman", suraNameAr: "لقمان", suraVerses: 34),
    Suramodel(suraNumber: 32, suraNameEn: "As-Sajda", suraNameAr: "السجدة", suraVerses: 30),
    Suramodel(suraNumber: 33, suraNameEn: "Al-Ahzab", suraNameAr: "الأحزاب", suraVerses: 73),
    Suramodel(suraNumber: 34, suraNameEn: "Saba", suraNameAr: "سبأ", suraVerses: 54),
    Suramodel(suraNumber: 35, suraNameEn: "Fatir", suraNameAr: "فاطر", suraVerses: 45),
    Suramodel(suraNumber: 36, suraNameEn: "Ya-Sin", suraNameAr: "يس", suraVerses: 83),
    Suramodel(suraNumber: 37, suraNameEn: "As-Saffat", suraNameAr: "الصافات", suraVerses: 182),
    Suramodel(suraNumber: 38, suraNameEn: "Sad", suraNameAr: "ص", suraVerses: 88),
    Suramodel(suraNumber: 39, suraNameEn: "Az-Zumar", suraNameAr: "الزمر", suraVerses: 75),
    Suramodel(suraNumber: 40, suraNameEn: "Ghafir", suraNameAr: "غافر", suraVerses: 85),
    Suramodel(suraNumber: 41, suraNameEn: "Fussilat", suraNameAr: "فصّلت", suraVerses: 54),
    Suramodel(suraNumber: 42, suraNameEn: "Ash-Shura", suraNameAr: "الشورى", suraVerses: 53),
    Suramodel(suraNumber: 43, suraNameEn: "Az-Zukhruf", suraNameAr: "الزخرف", suraVerses: 89),
    Suramodel(suraNumber: 44, suraNameEn: "Ad-Dukhan", suraNameAr: "الدّخان", suraVerses: 59),
    Suramodel(suraNumber: 45, suraNameEn: "Al-Jathiya", suraNameAr: "الجاثية", suraVerses: 37),
    Suramodel(suraNumber: 46, suraNameEn: "Al-Ahqaf", suraNameAr: "الأحقاف", suraVerses: 35),
    Suramodel(suraNumber: 47, suraNameEn: "Muhammad", suraNameAr: "محمد", suraVerses: 38),
    Suramodel(suraNumber: 48, suraNameEn: "Al-Fath", suraNameAr: "الفتح", suraVerses: 29),
    Suramodel(suraNumber: 49, suraNameEn: "Al-Hujurat", suraNameAr: "الحجرات", suraVerses: 18),
    Suramodel(suraNumber: 50, suraNameEn: "Qaf", suraNameAr: "ق", suraVerses: 45),
    Suramodel(suraNumber: 51, suraNameEn: "Adh-Dhariyat", suraNameAr: "الذاريات", suraVerses: 60),
    Suramodel(suraNumber: 52, suraNameEn: "At-Tur", suraNameAr: "الطور", suraVerses: 49),
    Suramodel(suraNumber: 53, suraNameEn: "An-Najm", suraNameAr: "النجم", suraVerses: 62),
    Suramodel(suraNumber: 54, suraNameEn: "Al-Qamar", suraNameAr: "القمر", suraVerses: 55),
    Suramodel(suraNumber: 55, suraNameEn: "Ar-Rahman", suraNameAr: "الرحمن", suraVerses: 78),
    Suramodel(suraNumber: 56, suraNameEn: "Al-Waqi'a", suraNameAr: "الواقعة", suraVerses: 96),
    Suramodel(suraNumber: 57, suraNameEn: "Al-Hadid", suraNameAr: "الحديد", suraVerses: 29),
    Suramodel(suraNumber: 58, suraNameEn: "Al-Mujadila", suraNameAr: "المجادلة", suraVerses: 22),
    Suramodel(suraNumber: 59, suraNameEn: "Al-Hashr", suraNameAr: "الحشر", suraVerses: 24),
    Suramodel(suraNumber: 60, suraNameEn: "Al-Mumtahina", suraNameAr: "الممتحنة", suraVerses: 13),
    Suramodel(suraNumber: 61, suraNameEn: "As-Saff", suraNameAr: "الصف", suraVerses: 14),
    Suramodel(suraNumber: 62, suraNameEn: "Al-Jumu'a", suraNameAr: "الجمعة", suraVerses: 11),
    Suramodel(suraNumber: 63, suraNameEn: "Al-Munafiqun", suraNameAr: "المنافقون", suraVerses: 11),
    Suramodel(suraNumber: 64, suraNameEn: "At-Taghabun", suraNameAr: "التغابن", suraVerses: 18),
    Suramodel(suraNumber: 65, suraNameEn: "At-Talaq", suraNameAr: "الطلاق", suraVerses: 12),
    Suramodel(suraNumber: 66, suraNameEn: "At-Tahrim", suraNameAr: "التحريم", suraVerses: 12),
    Suramodel(suraNumber: 67, suraNameEn: "Al-Mulk", suraNameAr: "الملك", suraVerses: 30),
    Suramodel(suraNumber: 68, suraNameEn: "Al-Qalam", suraNameAr: "القلم", suraVerses: 52),
    Suramodel(suraNumber: 69, suraNameEn: "Al-Haqqah", suraNameAr: "الحاقة", suraVerses: 52),
    Suramodel(suraNumber: 70, suraNameEn: "Al-Ma'arij", suraNameAr: "المعارج", suraVerses: 44),
    Suramodel(suraNumber: 71, suraNameEn: "Nuh", suraNameAr: "نوح", suraVerses: 28),
    Suramodel(suraNumber: 72, suraNameEn: "Al-Jinn", suraNameAr: "الجن", suraVerses: 28),
    Suramodel(suraNumber: 73, suraNameEn: "Al-Muzzammil", suraNameAr: "المزّمّل", suraVerses: 20),
    Suramodel(suraNumber: 74, suraNameEn: "Al-Muddathir", suraNameAr: "المدّثر", suraVerses: 56),
    Suramodel(suraNumber: 75, suraNameEn: "Al-Qiyamah", suraNameAr: "القيامة", suraVerses: 40),
    Suramodel(suraNumber: 76, suraNameEn: "Al-Insan", suraNameAr: "الإنسان", suraVerses: 31),
    Suramodel(suraNumber: 77, suraNameEn: "Al-Mursalat", suraNameAr: "المرسلات", suraVerses: 50),
    Suramodel(suraNumber: 78, suraNameEn: "An-Naba'", suraNameAr: "النبأ", suraVerses: 40),
    Suramodel(suraNumber: 79, suraNameEn: "An-Nazi'at", suraNameAr: "النازعات", suraVerses: 46),
    Suramodel(suraNumber: 80, suraNameEn: "Abasa", suraNameAr: "عبس", suraVerses: 42),
    Suramodel(suraNumber: 81, suraNameEn: "At-Takwir", suraNameAr: "التكوير", suraVerses: 29),
    Suramodel(suraNumber: 82, suraNameEn: "Al-Infitar", suraNameAr: "الإنفطار", suraVerses: 19),
    Suramodel(suraNumber: 83, suraNameEn: "Al-Mutaffifin", suraNameAr: "المطفّفين", suraVerses: 36),
    Suramodel(suraNumber: 84, suraNameEn: "Al-Inshiqaq", suraNameAr: "الإنشقاق", suraVerses: 25),
    Suramodel(suraNumber: 85, suraNameEn: "Al-Buruj", suraNameAr: "البروج", suraVerses: 22),
    Suramodel(suraNumber: 86, suraNameEn: "At-Tariq", suraNameAr: "الطارق", suraVerses: 17),
    Suramodel(suraNumber: 87, suraNameEn: "Al-A'la", suraNameAr: "الأعلى", suraVerses: 19),
    Suramodel(suraNumber: 88, suraNameEn: "Al-Ghashiyah", suraNameAr: "الغاشية", suraVerses: 26),
    Suramodel(suraNumber: 89, suraNameEn: "Al-Fajr", suraNameAr: "الفجر", suraVerses: 30),
    Suramodel(suraNumber: 90, suraNameEn: "Al-Balad", suraNameAr: "البلد", suraVerses: 20),
    Suramodel(suraNumber: 91, suraNameEn: "Ash-Shams", suraNameAr: "الشمس", suraVerses: 15),
    Suramodel(suraNumber: 92, suraNameEn: "Al-Lail", suraNameAr: "الليل", suraVerses: 21),
    Suramodel(suraNumber: 93, suraNameEn: "Ad-Duha", suraNameAr: "الضحى", suraVerses: 11),
    Suramodel(suraNumber: 94, suraNameEn: "Ash-Sharh", suraNameAr: "الشرح", suraVerses: 8),
    Suramodel(suraNumber: 95, suraNameEn: "At-Tin", suraNameAr: "التين", suraVerses: 8),
    Suramodel(suraNumber: 96, suraNameEn: "Al-Alaq", suraNameAr: "العلق", suraVerses: 19),
    Suramodel(suraNumber: 97, suraNameEn: "Al-Qadr", suraNameAr: "القدر", suraVerses: 5),
    Suramodel(suraNumber: 98, suraNameEn: "Al-Bayyina", suraNameAr: "البينة", suraVerses: 8),
    Suramodel(suraNumber: 99, suraNameEn: "Az-Zalzalah", suraNameAr: "الزلزلة", suraVerses: 8),
    Suramodel(suraNumber: 100, suraNameEn: "Al-Adiyat", suraNameAr: "العاديات", suraVerses: 11),
    Suramodel(suraNumber: 101, suraNameEn: "Al-Qari'a", suraNameAr: "القارعة", suraVerses: 11),
    Suramodel(suraNumber: 102, suraNameEn: "At-Takathur", suraNameAr: "التكاثر", suraVerses: 8),
    Suramodel(suraNumber: 103, suraNameEn: "Al-Asr", suraNameAr: "العصر", suraVerses: 3),
    Suramodel(suraNumber: 104, suraNameEn: "Al-Humazah", suraNameAr: "الهمزة", suraVerses: 9),
    Suramodel(suraNumber: 105, suraNameEn: "Al-Fil", suraNameAr: "الفيل", suraVerses: 5),
    Suramodel(suraNumber: 106, suraNameEn: "Quraysh", suraNameAr: "قريش", suraVerses: 4),
    Suramodel(suraNumber: 107, suraNameEn: "Al-Ma'un", suraNameAr: "الماعون", suraVerses: 7),
    Suramodel(suraNumber: 108, suraNameEn: "Al-Kawthar", suraNameAr: "الكوثر", suraVerses: 3),
    Suramodel(suraNumber: 109, suraNameEn: "Al-Kafirun", suraNameAr: "الكافرون", suraVerses: 6),
    Suramodel(suraNumber: 110, suraNameEn: "An-Nasr", suraNameAr: "النصر", suraVerses: 3),
    Suramodel(suraNumber: 111, suraNameEn: "Al-Masad", suraNameAr: "المسد", suraVerses: 5),
    Suramodel(suraNumber: 112, suraNameEn: "Al-Ikhlas", suraNameAr: "الإخلاص", suraVerses: 4),
    Suramodel(suraNumber: 113, suraNameEn: "Al-Falaq", suraNameAr: "الفلق", suraVerses: 5),
    Suramodel(suraNumber: 114, suraNameEn: "An-Nas", suraNameAr: "الناس", suraVerses: 6),
  ];
 static List<Onboardingmodel> OnboardingList =[
   Onboardingmodel(image: Assetsmanager.Onboarding1,
       desc: StringManager.Onboardingdes1),
   Onboardingmodel(image: Assetsmanager.Onboarding2,
       desc:StringManager.Onboardingdes2,title: StringManager.Onboardingtit2),
   Onboardingmodel(image: Assetsmanager.Onboarding3,
       desc:StringManager.Onboardingdes3,title: StringManager.Onboardingtit3),
   Onboardingmodel(image: Assetsmanager.Onboarding4,
 desc:StringManager.Onboardingdes4,title: StringManager.Onboardingtit4),
   Onboardingmodel(image: Assetsmanager.Onboarding5,
 desc:StringManager.Onboardingdes5,title: StringManager.Onboardingtit5),
 ];
 static List<String> zekrList=[
   StringManager.Zakr1,
   StringManager.Zakr2,
   StringManager.Zakr3,
   StringManager.Zakr4,

 ];

}